language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

addons:
  hosts:
    - "mail-sender.dev"

env:
  - MAIL_SENDER_ENV=travis

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

before_install:
    - composer install -o -n -q

install:
    - wget http://selenium-release.storage.googleapis.com/2.46/selenium-server-standalone-2.46.0.jar

before_script:
    - mysql -e "create database IF NOT EXISTS `mail-sender`;" -uroot
    - mysql -uroot 'mail-sender' < mail-sender.sql
    - nohup php -S "mail-sender.dev:80" -t web > server.log 2>&1 &
    - sh -e /etc/init.d/xvfb start
    - export DISPLAY=:99.0
    - java -jar selenium-server-standalone-2.46.0.jar > /dev/null 2>&1 &
    - sleep 5

script:
    - bin/phpunit

after_failure:
    - cat server.log
